### PR TITLE
Fix undefined behaviour in BindGroupTracker when passing no dynamic offsets

### PR DESCRIPTION
**Pull request by silversquirl**
This is a pending CL being sent upstream to dawn.googlesource.com.

Status:

* [ ] CL sent: TODO
* [ ] Merged into our main branch

Helps https://github.com/hexops/mach/issues/221

### CODE REVIEW

**Comment by silversquirl** [comment]
@slimsag Should I have PR'd this to the `upstream` branch instead? I'm not 100% clear on how this repo is organized :)

**Comment by slimsag** [comment]
@silversquirl Thanks for sending this, I had missed it, sorry!

I will merge this into the `main` branch soon and release this in `mach/gpu`.

We will also need to send a CL to https://dawn.googlesource.com/dawn/ - the patch is only temporary here, we won't have a long-lived fork. Are you interested in sending that CL, or would you like me to? Happy either way!

**Comment by silversquirl** [comment]
Would be great if you're up for sending in the CL! Thanks :)

**Comment by slimsag** [comment]
@silversquirl Could you do me a favor and resend this but targetting the `upstream` branch? That way it stays open and I have a reminder to send the CL upstream

**Pull request merged**
